### ISSUE TITLE
Include vendor specific browser globals?

### ISSUE THREAD

**Issue by Mr0grog** [sindresorhus/globals#105]
I’m currently working on a project that uses a variety of WebKit-specific globals when they are available, e.g. `WebKitPoint`. Would it be reasonable to include those here?

In general, is there a policy on the inclusion of vendor-prefixed globals (things intended to be or on their way to standardization) or vendor-specific globals (things only available on a given platform)?

**Comment by sindresorhus** [comment]
I don't think we want to include more prefixed globals. At least Chrome have stopped doing vendor prefixes in favor of other ways of trying out new API's.

Up to @nzakas though.

**Comment by nzakas** [comment]
Yeah, I'd prefer not to include vendor-prefixed globals.

**Comment by Mr0grog** [comment]
Ok, will close :thumbsup:
