### ISSUE TITLE
Jest and Jasmine globals should be mutually exclusive

### ISSUE THREAD

**Issue by ncuillery** [sindresorhus/globals#106]
First line of the README.md (https://www.npmjs.com/package/jest-cli)

> **Adaptable:** Jest uses Jasmine assertions by default and Jest is modular, extendible and configurable.

Jest entry should contain only its own global vars (`jest`, `gen`, few others,...)

Users would have to declare both `jest` and `jasmine` env if they used Jest with Jasmine. 
It would be more respectful of the Jest's architecture and easier to maintain here (Jest and Jasmine entries are actually quite a mess 😥 ).

**Comment by ncuillery** [comment]
Ping @cpojer What do you think ?

**Comment by cpojer** [comment]
I don't think we should do this. For now Jest only supports Jasmine and in the future it may support other test runners but it is unlikely we'll add more globals. I see no reasons to make this breaking change.
