### ISSUE TITLE
ES8 environment

### ISSUE THREAD

**Issue by not-an-aardvark** [sindresorhus/globals#111]
The [shared memory proposal](https://github.com/tc39/ecmascript_sharedmem) has reached stage 4, so ES2017 will have two new builtin globals: `Atomics` and `SharedArrayBuffer`.

I saw in the readme that this package is no longer accepting new environments. Does that also apply to environments for new standardized JS globals?

If the new environment will be added to this package, what should it be called? `es8` would be consistent with the existing `es6` environment, but `es2017` is the canonical name for the spec.

**Comment by sindresorhus** [comment]
New globals are added when they are in at least one stable browser unprefixed. As to where to put them, that's up to ESLint. I would rename `es6` to `es2015` and then add it in `es2017`. ESLint can handle the name conversion internally.

**Comment by not-an-aardvark** [comment]
> As to where to put them, that's up to ESLint.

I'm not sure I understand this -- isn't `globals` a standalone package? (I'm not very familiar with the relationship between `globals` and ESLint.)

**Comment by sindresorhus** [comment]
@not-an-aardvark Yes, but ESLint is the main consumer.

**Comment by not-an-aardvark** [comment]
Ok, thanks. In any case, I'll close this until `Atomics` and `SharedArrayBuffer` are implemented in a browser.
