### ISSUE TITLE
GLOBAL and root

### ISSUE THREAD

**Issue by eight04** [sindresorhus/globals#117]
These two variables are deprecated in node v6.0.0: https://github.com/nodejs/node/pull/1838 which are never documented and should be safe to remove. By removing `root` from node's env, it should help those developers that accidentally access global `root` variable.

I also filed an issue in ESLint: https://github.com/eslint/eslint/issues/9144

**Comment by sindresorhus** [comment]
Agreed. Those were never documented and I doubt anyone is actually using them.
