### ISSUE TITLE
Why is indexedDB listed as a browser global, but not other associated things like IDBKeyRange?

### ISSUE THREAD

**Issue by dumbmatter** [sindresorhus/globals#12]
There are several other IndexedDB-related globals besides just `indexedDB`, most notably `IDBKeyRange` which is used very commonly. Should all of these IndexedDB globals be listed here? Just the ones that are commonly used? None of them?

**Comment by es128** [comment]
+1 to adding every web api variable that may be available in a browser's global scope including all the IDB* ones

https://developer.mozilla.org/en-US/docs/Web/API

**Comment by sindresorhus** [comment]
:+1: Lol, who decided it was a good idea to introduce a gadzillion globals for IDB...

**Comment by sindresorhus** [comment]
@nzakas agree?

**Comment by nzakas** [comment]
:+1:

**Comment by nzakas** [comment]
I'll add them
