### ISSUE TITLE
'serviceworker' doesn't include everything from 'worker'

### ISSUE THREAD

**Issue by TBBle** [sindresorhus/globals#133]
I just noticed, while setting up a new project, that the `serviceworker` list doesn't appear to include `URL` and `fetch`, while `worker` does. Since 'serviceworker' inherits from `worker`, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope), this seems incorrect to me.

It's also possible I'm misunderstanding the issue. It also seems at a short glance that #82 will introduce inheritance so this would be magically solved in the future.

**Comment by TBBle** [comment]
I've just realised that perhaps the intention is that the user must mark the file with both environments, since the `serviceworker` definition only includes those things that aren't included in `worker`.

```javascript
/* eslint-env worker */
/* eslint-env serviceworker */
```

If that's the case, feel free to close this issue.

**Comment by sindresorhus** [comment]
You should not have to specify both. This is just an oversight.
