### ISSUE TITLE
external is not a global variable for Safari 11.1 (Mac OSX) or iOS 11.3

### ISSUE THREAD

**Issue by coreylight** [sindresorhus/globals#135]
`window.external` does not seem exist for these browsers, causing consuming packages (eslint) to not properly catch bad code.

**Comment by sindresorhus** [comment]
We get the globals from latest Chrome. I have no idea what `window.external` is supposed to be though.

**Comment by daurnimator** [comment]
@sindresorhus was this fixed? (I don't see a commit)

**Comment by sindresorhus** [comment]
There’s nothing to fix.

**Comment by daurnimator** [comment]
oh sorry, I thought this was a different issue.
