### ISSUE TITLE
Add console as browser global

### ISSUE THREAD

**Issue by nzakas** [sindresorhus/globals#14]
Not sure how this was missed, but the browser environment is missing `console` as a global. We should add that.

**Comment by sindresorhus** [comment]
It's under [`devel`](https://github.com/sindresorhus/globals/blob/c8983a2af7c74cec00066597e2858b90b8670533/globals.json#L404) together with some other ones like `alert` and `prompt`. Should we maybe drop `devel` and move them into `browser`?

// @es128

**Comment by nzakas** [comment]
Yeah, I don't think having them in a separate environment makes sense. 

`opera` I've used before. No idea about `Debug`.

**Comment by sindresorhus** [comment]
What did you use `opera` for? Just curious.

**Comment by es128** [comment]
Yeah we have `console` listed under `node`. :+1: The `devel` section ought to be combined into `browser`.

`Debug` appears to be an old IE thing: http://msdn.microsoft.com/en-us/library/ie/bs12a9wf%28v=vs.94%29.aspx (that was not an easy thing to google for)

**Comment by nzakas** [comment]
`opera` was used for browser detection...of Opera. It used to be the only way to get the actual version of Opera (due to all the spoofing it used to do).

**Comment by nzakas** [comment]
I'll merge the sections

**Comment by nzakas** [comment]
Pushing a new version (major bump)
