### ISSUE TITLE
Cannot to deep.nested on an array, have to wrap it with an object

### ISSUE THREAD

**Issue by Noitidart** [sindresorhus/globals#148]
This was a stackoverflow question - https://stackoverflow.com/q/53906051/1828637

He has a `const payload = [{ id: 0 },{ id: 1 }]` and wants to do the following:

    expect(payload).to.nested.include({
      '[0].id': 0,
      '[1].id': 1
    });

But it does not work. He has to wrap it to get this to work:

    const wrappedPayload = { a: payload };
    expect(wrappedPayload).to.nested.include({
      'a[0].id': 0,
      'a[1].id': 1
    });

I think this is a bug.

**Comment by nzakas** [comment]
Hi there! This repository is for the `globals` package, and it doesn't appear that this question is related to this package, so I'm closing the issue.

**Comment by Noitidart** [comment]
Oops! lol
