### ISSUE TITLE
Create ESM environment for node

### ISSUE THREAD

**Issue by jkrems** [sindresorhus/globals#159]
Right now the globals for node include identifiers that aren't real globals but are artifacts of the fact that historically most code has been running inside of CommonJS wrapper functions.

A "true" globals environment for node may look like this:

```diff
 	"node": {
-		"__dirname": false,
-		"__filename": false,
 		"Buffer": false,
 		"clearImmediate": false,
 		"clearInterval": false,
 		"clearTimeout": false,
 		"console": false,
-		"exports": true,
 		"global": false,
 		"Intl": false,
-		"module": false,
 		"process": false,
 		"queueMicrotask": false,
-		"require": false,
 		"setImmediate": false,
 		"setInterval": false,
 		"setTimeout": false,
 		"TextDecoder": false,
 		"TextEncoder": false,
 		"URL": false,
 		"URLSearchParams": false
 	},
```

Since the name "node" is already taken, maybe it could be called "nodeBase"? Or "nodeButOnlyTheActualGlobals". I honestly don't have a good name yet.

Happy to create a PR if the overall direction makes sense.

**Comment by imme-emosol** [comment]
Does https://github.com/sindresorhus/globals/pull/160 close/resolve this issue?

**Comment by fisker** [comment]
Yes, #160 fixed it, `globals.nodeBuiltin` is what we want. Thanks!
