### ISSUE TITLE
Add Tampermonkey/Violentmonkey supported globals to Greasemonkey

### ISSUE THREAD

**Issue by minig0d** [sindresorhus/globals#162]
Since Tampermonkey / Violentmonkey utilization vastly exceeds the original Greasemonkey, Greasemonkey doesn't seem to be very actively developed anymore, and most people consider them nearly the same, would be great to add the few missing globals so separate environments didn't need to be created for the minor differences:

- GM_addValueChangeListener (TM/VM)
- GM_download (TM/VM)
- GM_getTab (TM only?)
- GM_getTabs (TM only?)
- GM_notification (TM/VM)
- GM_removeValueChangeListener (TM/VM)
- GM_saveTab (TM only?)
- GM_unregisterMenuCommand (TM/VM)

Source:
TM: [https://www.tampermonkey.net/documentation.php#api](https://www.tampermonkey.net/documentation.php#api)
VM: [https://violentmonkey.github.io/api/gm/](https://violentmonkey.github.io/api/gm/)

**Comment by sindresorhus** [comment]
I agree. PR welcome.
