### ISSUE TITLE
Found 17 global variables with my module.

### ISSUE THREAD

**Issue by shapkarin** [sindresorhus/globals#164]
Hello. I want to use your package for my one. Not sure if that is not exist already. But anyway.
The problem that when I start to test [my package](https://github.com/shapkarin/global-diff) I found 17 global vars in the chrome incognito mode.
Here is the list:
```js
0: "onformdata"
1: "onwebkitanimationend"
2: "onwebkitanimationiteration"
3: "onwebkitanimationstart"
4: "onwebkittransitionend"
5: "onselectstart"
6: "onselectionchange"
7: "captureEvents"
8: "releaseEvents"
9: "webkitRequestAnimationFrame"
10: "webkitCancelAnimationFrame"
11: "webkitStorageInfo"
12: "chrome"
13: "onpointerrawupdate"
14: "webkitRequestFileSystem"
15: "webkitResolveLocalFileSystemURL"
16: "trustedTypes"
```
I forked your repo and want to add them if they all are the default now for Chrome too.

**Comment by shapkarin** [comment]
I will try to provide a PR

**Comment by shapkarin** [comment]
I opened PR. But that a little bit strange that with yours plugin I got more global variables than 14 at issue #164 maybe it's some bug in my code as well. But I hope that I help you yo update your list with that PR in any case.

**Comment by shapkarin** [comment]
some of they are in a black list. but maybe some other should be. anyway I helped community to automate that browsers global variables part. Maybe that will helps.

**Comment by sindresorhus** [comment]
We now automatically generate the globals, so this should no longer be a concern.
