### ISSUE TITLE
Fix get-browser-globals.js and add additional update scripts for browser's environment.

### ISSUE THREAD

**Issue by shapkarin** [sindresorhus/globals#166]
I think that yours `get-browser-globals.js` don't works well test. Here what I got:
- run script from `get-browser-globals.js`
- copy my code to the json file
- run `npm run  test`
- get an error that `upperCase` letter must be `before LowerCased`

So I also fix the get-browser-globals.js script to avoid that.

**Comment by fisker** [comment]
`get-browser-globals.js` has been updated.
