### ISSUE TITLE
Add all standard DOM events in the browser environment

### ISSUE THREAD

**Issue by ncuillery** [sindresorhus/globals#19]
Hi,

What's your feeling about adding all the [standard DOM events](https://developer.mozilla.org/en-US/docs/Web/API/Event) in the `browser` environment ?

Currently, there is only Event, CustomEvent and MouseEvent in it.

**Comment by sindresorhus** [comment]
Oh my. Much globals. I've never even heard of most of these, but yeah, I guess it makes sense to add them.

**Comment by es128** [comment]
+1 anything from that Web API reference currently missing should be added.

Potentially excepting some of the experimental stuff, but I'd say no, we should add all of it.

**Comment by nzakas** [comment]
:+1:

**Comment by sindresorhus** [comment]
@ncuillery Can you do a PR?

**Comment by ncuillery** [comment]
Ok, it will arrive soon

**Comment by ncuillery** [comment]
See #21
