### ISSUE TITLE
`NodeRequire` is missing from node

### ISSUE THREAD

**Issue by robertIsaac** [sindresorhus/globals#201]

**Comment by sindresorhus** [comment]
```
❯ node
Welcome to Node.js v20.5.0.
Type ".help" for more information.
> NodeRequire
Uncaught ReferenceError: NodeRequire is not defined
```

**Comment by robertIsaac** [comment]
> ```
> ❯ node
> Welcome to Node.js v20.5.0.
> Type ".help" for more information.
> > NodeRequire
> Uncaught ReferenceError: NodeRequire is not defined
> ```

how to correctly use https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules__types_node_globals_d_.noderequire.html

here is the code snippet giving me the error
```
// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
```

**Comment by fregante** [comment]
That's just a type, not an actual global
