### ISSUE TITLE
package types return `any` if the project's tsconfig does not enable `resolveJsonModule: true`

### ISSUE THREAD

**Issue by bradzacher** [sindresorhus/globals#208]
What it says on the tin really - if the consuming project doesn't use `resolveJsonModule: true` then typescript won't resolve the types for the JSON file.

```
Cannot find module './globals.json'. Consider using '--resolveJsonModule' to import module with '.json' extension. (2732)
```

This error can easily be hidden as well if the project uses `skipLibCheck` - leading to a silent `any` for the import.

**Suggested Fix**

Pre-generating the types for the JSON blob at build time would enable anyone to use this, but would require some work.
Alternately documenting the requirement in the readme would help during installation so people can understand the requirements.

**Comment by voxpelli** [comment]
Fixed by #209 which removes the reliance on the JSON-file for the types
