### ISSUE TITLE
AudioWorkletProcessor removed from globals.browser?

### ISSUE THREAD

**Issue by patwork** [sindresorhus/globals#248]
Hello,

Why AudioWorkletProcessor and registerProcessor have been removed from globals in https://github.com/sindresorhus/globals/pull/224 ?

They are part of Web Audio API https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor

```javascript
// white-noise-processor.js
class WhiteNoiseProcessor extends AudioWorkletProcessor {
  [....]
}
registerProcessor("white-noise-processor", WhiteNoiseProcessor);
```

If they are not among the standard global variables in browsers, is it possible to create a new list for them, for example globals.worklets or globals.browser.worklets, etc?

**Comment by fisker** [comment]
Sorry for removing that, I think it's fine to add back to browser globals, but we use [script](https://github.com/sindresorhus/globals/blob/main/scripts/get-browser-globals.mjs) to build the data now, better to find a way to get the worklet globals.
