### ISSUE TITLE
`Iterator` should in ES* files

### ISSUE THREAD

**Issue by skyclouds2001** [sindresorhus/globals#266]
currently `Iterator` is in https://github.com/sindresorhus/globals/blob/main/data/worker.mjs#L136, https://github.com/sindresorhus/globals/blob/main/data/nodeBuiltin.mjs#L32, but not in any of the ES* file

it is a JavaScript interface available in all scope, so it is better to place it in ES* file

also, it is not in browser.mjs or serviceworker.mjs currently

**Comment by fisker** [comment]
"Iterator Helpers" reached stage 4 yesterday, but [the spec](https://262.ecma-international.org/15.0/index.html) has not include `Iterator` yet.

**Comment by fisker** [comment]
Guess this will get merged soon. https://github.com/tc39/ecma262/pull/3395
