### ISSUE TITLE
`AudioWorkletGlobalScope` has a trailing space (again)

### ISSUE THREAD

**Issue by jonahallibone** [sindresorhus/globals#268]
The source doesn't seem to have this error but when I have `"globals": "^15.11.0",` as a `devDependency`, I can clearly see 
```
"AudioWorkletGlobalScope ": false
```
in my `node_modules`

<img width="319" alt="Screenshot 2024-10-17 at 12 06 25 PM" src="https://github.com/user-attachments/assets/88c45cd3-d232-4b8e-b1aa-0aac992de3ec">

**Comment by fisker** [comment]
Can you check the package.json file in the same dir where you open the `globals.json` file?

**Comment by jonahallibone** [comment]
@fisker 
```
{
	"name": "globals",
	"version": "11.12.0",
	"description": "Global identifiers from different JavaScript environments",
	"license": "MIT",
	"repository": "sindresorhus/globals",
	"author": {
		"name": "Sindre Sorhus",
		"email": "sindresorhus@gmail.com",
		"url": "sindresorhus.com"
	},
	"engines": {
		"node": ">=4"
	},
	"scripts": {
		"test": "xo && ava"
	},
	"files": [
		"index.js",
		"globals.json"
	],
	"keywords": [
		"globals",
		"global",
		"identifiers",
		"variables",
		"vars",
		"jshint",
		"eslint",
		"environments"
	],
	"devDependencies": {
		"ava": "0.21.0",
		"xo": "0.18.0"
	},
	"xo": {
		"ignores": [
			"get-browser-globals.js"
		]
	}
}

```

**Comment by fisker** [comment]
Not sure, if you are using yarn, maybe you can use `yarn why globals` to find out.

**Comment by jonahallibone** [comment]
Using npm but I'll try to uninstall and reinstall

**Comment by Christoph142** [comment]
@jonahallibone various packages specify an outdated version of globals as their dependency, e.g. eslint and babel.
Adding an override to package.json file to force version 15 over 14 and 11 respectively fixed it for me:
```
"@eslint/eslintrc": {
  "globals": ">=14"
},
"@babel/traverse": {
  "globals": ">=14"
}
```
