### ISSUE TITLE
AudioWorkletGlobalScope trailing space

### ISSUE THREAD

**Issue by isbosykh** [sindresorhus/globals#270]
Can't run eslint because of the `TypeError: Key "languageOptions": Key "globals": Global "AudioWorkletGlobalScope " has leading or trailing whitespace.`. And it is in your `globals.json` 255:30.

![image](https://github.com/user-attachments/assets/a8dfc2c9-4ae5-4e5e-9a38-d9618479924c)

**Comment by isbosykh** [comment]
Well anyway it's not in your current version. It's one of the sub-deps. Closed.

**Comment by tigrr** [comment]
If you are here and getting this error because one of your dependencies uses that problematic version `11.0.0`, you can use
```json
    "overrides": {
        "globals": "14.0.0"
    }
```
in your `package.json`.
