### ISSUE TITLE
escape and unescape

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/globals#35]
These are in the `nonstandard` environment, which currently isn't imported by eslint. As they are not going away anytime soon and are defined in node and the browser, I think they belong in the `builtin` category.

Another approach would be that eslint imports this `nonstandard` environment where needed, but I'm more in favor of removing the `nonstandard` category all together. Opinions?

**Comment by kevva** [comment]
According to MDN:

> This feature has been removed from the Web standards.

But yeah, I'm not opposed to removing `nonstandard` and moving them to the `builtin` category either, since they still work.

**Comment by silverwind** [comment]
Yeah, they have been deprecated on the web for ages, but no browser dares to make the move to remove them as they'd be breaking the web basically ;)

**Comment by sindresorhus** [comment]
> I think they belong in the builtin category.

I guess this makes sense. They're actually defined in the ES spec in the (normative) Annex B for Additional ECMAScript Features for Web Browsers section.

**Comment by silverwind** [comment]
Has been landed in https://github.com/sindresorhus/globals/commit/7bbb6a23a6a401641f00a86597dbf87a579b2804, thanks.

**Comment by sindresorhus** [comment]
Gonna wait on @nzakas to :+1: before doing a release.

**Comment by silverwind** [comment]
Yeah of course.

Did a bit more research and I think this category was inherited from jshint. If jshint is ever going to use `globals`, they'd have to drop the [`nonstandard`](http://jshint.com/docs/options/#nonstandard) option. Purely from a jshint integration standpoint, it'd probably be better to keep the category and enable `nonstandard` in eslint itself, but let's hear what @nzakas thinks about this.

**Comment by sindresorhus** [comment]
I don't really care what JSHint does tbh. I'd rather this package be as good as possible. Can be easily shimmed by moving those props manually to a `nonstandard` prop by the consumer.

**Comment by nzakas** [comment]
:+1:
