### ISSUE TITLE
EventSource

### ISSUE THREAD

**Issue by Mr0grog** [sindresorhus/globals#38]
EventSource should be an available global for browser environments: https://html.spec.whatwg.org/multipage/comms.html#the-eventsource-interface

Happy to make a PR.

**Comment by Mr0grog** [comment]
(That said, it’s not implemented in any version of IE yet, including Edge. Not sure if that makes a difference here.)

**Comment by nzakas** [comment]
I'm sure they will get to it. It's already in every other browser. :+1:

**Comment by arthurvr** [comment]
Sounds good :+1:

**Comment by Mr0grog** [comment]
Thanks, PR-ing!
