### ISSUE TITLE
Convince JSHint to use this module

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/globals#4]
Would be nice to have parity between them.

_Now included in ESLint. Still need to convince JSHint though._

**Comment by es128** [comment]
Half of this issue is resolved: https://github.com/eslint/eslint/releases/tag/v0.11.0

**Comment by sindresorhus** [comment]
Woot :)

**Comment by valorkin** [comment]
@nzakas please review PR #17

**Comment by montogeek** [comment]
Since JShint joined ESLint, is this necessary?

**Comment by sindresorhus** [comment]
@montogeek JSHint did not join ESLint.

**Comment by montogeek** [comment]
@sindresorhus Correct, sorry :)

**Comment by sindresorhus** [comment]
Closing as JSHint is no longer relevant.
