### ISSUE TITLE
Add Ember.Test methods

### ISSUE THREAD

**Issue by ismay** [sindresorhus/globals#42]
I was wondering if the [Ember.Test](http://emberjs.com/api/classes/Ember.Test.html) methods could be added to the globals. I'm currently manually adding them to my `globals` in `tests/.eslintrc` for an ember-cli project. But it would be nice to just use an `env` setting. Would you accept a pull request for them?

Related to: https://github.com/eslint/eslint/issues/2870

**Comment by sindresorhus** [comment]
I'm neutral. It's up to @nzakas whether he wants it in ESLint.

**Comment by es128** [comment]
I don't see why not. How is it different from the other test frameworks we cover here?

**Comment by ismay** [comment]
I don't know if that was a rhetorical question :), but these are Ember specific helpers that can be used to test an Ember application.

So methods like `.click()`, `.find()`, `.visit()`, etc. Don't know if these should be added under a global `Ember` env, or grouped under `Ember.Test`. I'll leave that decision up to @nzakas and @sindresorhus. and will be glad to submit a PR if there's a consensus.

**Comment by sindresorhus** [comment]
@ismay What are the globals Ember.Test expose?

**Comment by ismay** [comment]
I think I mistakenly called them `Ember.Test` methods by the way, since they're referred to as test helpers here: http://guides.emberjs.com/v1.13.0/testing/test-helpers/. Ember.Test is merely a container for an assortment of testing related functionality, and contains other methods besides just the test helpers.

So all the test helpers that are exposed as globals are:

## Asynchronous

* `click`
* `fillIn`
* `keyEvent`
* `triggerEvent`
* `visit`

## Synchronous

* `currentPath`
* `currentRouteName`
* `currentUrl`
* `find`

## Wait

* `andThen`

**Comment by nzakas** [comment]
I don't see any reason not to do this - there's already a bunch for other test frameworks.
