### ISSUE TITLE
node 'path' is not included in globals.json

### ISSUE THREAD

**Issue by Woile** [sindresorhus/globals#45]
Hi, I was using ESLint and it recommended me using **path.join** instead of concatenating strings, i changed it, but the linter told me **path** was not defined. A [quick search](https://nodejs.org/api/path.html) showed me that path belongs to node, I realized they were using this lib, so I searched here for the key and could not find **path** inside the globals.json

If you want, just tell me and I can make a pull request adding `"path": false`  inside `globals.json`. But first confirm me if path actually belongs to node (I dunno if i missed something).

See ya!

**Comment by nzakas** [comment]
`path` isn't a global variable, you need to require it:

```js
var path = require("path");
```

**Comment by Woile** [comment]
Thank you very much!

**Comment by cawoodm** [comment]
This is no longer true. `fs` and `path` are included as globals as of NodeJS 18.

**Comment by nzakas** [comment]
This issue is eight years old, so no point in updating it now. :)
