### ISSUE TITLE
What's the process for determining what is global?

### ISSUE THREAD

**Issue by pmcelhaney** [sindresorhus/globals#56]
I ran into a problem where [ESLint was not detecting the use of an undeclared variable, `Promise`](https://github.com/eslint/eslint/issues/4085). 

How do we determine what qualifies as a global? In this particular case, Promise is not a global in IE (or ES5). Should it be excluded? 

Should we have separate versions of globals.json for different versions of EcmaScript?

**Comment by pmcelhaney** [comment]
After looking into it a bit more I think the best course of action is to add a new environment, called "builtin-es5", that only includes the builtin variables from ES5. To be clear, we would not remove those variables from "builtin". We we simply create a new option, so users can choose between "builtin-es5" and "builtin".

**Comment by nzakas** [comment]
This conversation should take place in the ESLint repo, as it's not just about separating things out in the manner you suggest.
