### ISSUE TITLE
Add `expect` for "chai" (or just add `expect` for mocha since most people use chai with mocha)

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/globals#62]

**Comment by niftylettuce** [comment]
Right now I have to add `"expect": true` in `"globals"` of my `.eslintrc` file.

**Comment by niftylettuce** [comment]
Also `assert` is needed

**Comment by sindresorhus** [comment]
:-1: The `mocha` env should be purely Mocha globals. I've personally never used Chai with Mocha.

As for a `chai` env. I'll leave that up to @nzakas.

> Also assert is needed

Is that a Mocha global? I've always done `var assert = require('assert');`.

**Comment by niftylettuce** [comment]
its chai, chai.assert, chai.expect

**Comment by SamVerschueren** [comment]
Don't see the point of globals here

```js
var chai = require('chai');
var expect = chai.expect;
var assert = chai.assert;
...
```

**Comment by nzakas** [comment]
Agree with @sindresorhus, the only global that Chai creates is `chai`. There's no such thing as a global `assert` in Mocha or Chai.

**Comment by niftylettuce** [comment]
@nzakas @sindresorhus this is why -- because most people that use `mocha` use `chai` (at least from what I've seen).  here's my use case:

`test/mocha.opts`:
```opts
--recursive
--debug
--reporter spec
--bail
--check-leaks
--ui bdd
--require test/support/
test/**/*.test.js
```

`test/support/index.js`:
```js
// setup global chai methods
import chai from 'chai';
import dirtyChai from 'dirty-chai';
import checkChai from 'check-chai';
chai.config.includeStack = true;
chai.config.showDiff = true;
chai.use(dirtyChai);
chai.use(checkChai);
global.chai = chai;
global.AssertionError = chai.AssertionError;
global.Assertion = chai.Assertion;
global.expect = chai.expect;
global.assert = chai.assert;
```

`test/unit/example.test.js`:
```js
describe('sindresorhus', () => {

  it('should have `sindresorhus` defined', () => {
    expect(sindresorhus).to.exist(); // <---- here's where we use global
  });

});
```

There are quite a lot of people that have this issue because it's not a global with eslint.

Otherwise we have to define a global `chai` and then call `chai.expect` or `chai.assert` every time.

Or we have to put this at the top of all of our files:

```js
import chai from 'chai';
const expect = chai.expect;
const assert = chai.assert;
```

That's not that pretty.

<https://stackoverflow.com/questions/19191384/how-can-i-solve-referenceerror-expect-is-not-defined-error-message> (this is an issue posted not even on GitHub about this)

![screen shot 2015-11-28 at 9 46 40 am](https://cloud.githubusercontent.com/assets/523141/11452417/fa6f7a58-95b4-11e5-9fa8-0acb627924c5.png)

**Comment by niftylettuce** [comment]
Another use case -- if someone passes `--require chai-setup.js` to their `mocha`.  They'd have to go and still set `chai: true` as a global in their `.eslintrc`

**Comment by nzakas** [comment]
@niftylettuce Chai and Mocha are two separate libraries, there is no reason to artificially bundle them together.

Your example shows that you are creating globals from Chai, rather than Chai injecting them itself. Chai's [documentation](http://chaijs.com/) also shows that `chai` is the only injected global.

If you are using ESLint, then you can [manually define](http://eslint.org/docs/user-guide/configuring.html#specifying-globals) any globals you want. I suggest you do that to solve the problem with your setup.

**Comment by niftylettuce** [comment]
it is very common to use chai in all your mocha tests though. this is not
cool

**Comment by niftylettuce** [comment]
thanks though for responding

**Comment by IanVS** [comment]
```js
import chai from 'chai';
const expect = chai.expect;
const assert = chai.assert;
```

can be combined into:

```js
import {expect, assert} from 'chai';
```

Which really isn't ugly at all, and has the benefit of being explicit.

**Comment by niftylettuce** [comment]
nice, got cloudy vision from babel upgrade... ha... that would have made
this easier. def will use that!!!!

**Comment by nirgit** [comment]
I am using Grunt in order to run my Mocha tests.
You can try configuring the mochaTest in the grunt.initConfig, the following:


grunt.initConfig({
...
    mochaTest: {
      test: {
        options: {
          reporter: 'spec',
          **require: [function(){ global.assert = require('assert'); }],**
          captureFile: 'mocha-results.txt',
          quiet: false, 
          clearRequireCache: false
        },
        src: ['<%= test %>/**/*.js']
      },
...
}

then don't forget to:
grunt.loadNpmTasks('grunt-mocha-test');

and:
grunt.registerTask('test', ['mochaTest'])

to your gruntfile.js

then try running:

> grunt test

maybe it'll work.

**Comment by ExE-Boss** [comment]
I always explicitly use `chai.*` instead of calling the Chai function directly.
