### ISSUE TITLE
Worth creating a "qunit2" section which just contains the QUnit global?

### ISSUE THREAD

**Issue by platinumazure** [sindresorhus/globals#66]
According to the [QUnit 2.x Upgrade Guide][1], all of the globals except for `QUnit` are going to be deprecated in QUnit 2.0 and removed in QUnit 2.1. Is it worth creating a new "qunit2" section to reflect this?

Note that I have no idea when QUnit 2.0 is actually coming out, so if we agree that this is worth doing later but not now, that is fine too.

  [1]: http://qunitjs.com/upgrade-guide-2.x/

**Comment by es128** [comment]
What would be the difference at that point between expecting people to set a `qunit2` environment vs just specifying `QUnit` as an explicit global? Who benefits from a set with only one entry?

**Comment by platinumazure** [comment]
Well, that's why I asked "is it worth it" and opened it up to discussion. Your answer might be no. :smile:

My suggestion is that if the QUnit project decides to add another global variable somewhere in 2.x, then it would be easy to augment this repository and then anyone who directly consumes this repo gets it for free when they get the latest version of this package. (For example, if you run ESLint and you specify `qunit2: true` in environments, pretending for this scenario that qunit2 is implemented here and consumed as an environment by ESLint, then you don't have to explicitly add the other global once you upgrade ESLint and its globals version is sufficiently updated.) That said, I confess the *probability* of that scenario is quite low.

I'm not super attached to this. I just wanted to make sure a discussion occurred. That's all :smile:

**Comment by es128** [comment]
@platinumazure agreed. I was just reiterating your question in another way. Can anyone elaborate on how this proposal would add value to users?

I don't think the possibility of future globals maybe being introduced is enough justification.

**Comment by sindresorhus** [comment]
Yeah, I don't see the point :)
