### ISSUE TITLE
New browser globals

### ISSUE THREAD

**Issue by captainbrosset** [sindresorhus/globals#87]
The [Web Animations API spec](https://w3c.github.io/web-animations/) is being implemented in Firefox (parts have already shipped in FF46/47, and there's more to come) and Chrome (unsure about the version), and it's on Edge's roadmap.

This spec brings a number of new constructors available globally in a browser environment:

- KeyframeEffect
- KeyframeEffectReadOnly
- AnimationTimeline
- Animation
- AnimationEffectTiming
- AnimationEffectTimingReadOnly
- AnimationEffectReadOnly
- SharedKeyframeList

Maybe more that I have missed.
These should be added to the list of globals in this project. I'd be interested to contribute this if you let me know how to get started (seems like a simple enough change in the json file, but maybe I'm missing something).

It's my understanding that this is, in turn, used by eslint to validate script in browser environments.

**Comment by sindresorhus** [comment]
Yes, just do a pull request in the JSON file. The globals are alphabetically sorted.
